import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Question from '../components/Question'
export default function Home({data}) {
  const questions = (data.results)
  // console.log(questions)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {questions.map((item)=> <Question 
          question={item.question}
          correct_answer={item.correct_answer}
          incorrect_answer={item.incorrect_answers}
        />)}
      </main>

    </div>
  )
}
export async function getStaticProps(context) {
  const res = await fetch('https://opentdb.com/api.php?amount=10&category=27&difficulty=easy&type=multiple')
  const data = await res.json()
  return {
    props: {data}, // will be passed to the page component as props
  }
}
